const projectCategoryOptions = ["Backend", "Full Stack", "Frontend", "Automation", "Tool", "Other"];
const projectStatusOptions = ["Live", "In Progress", "Archived"];
const skillCategoryOptions = ["Backend", "Frontend", "Database", "Messaging", "DevOps", "Languages", "Tools", "Soft Skills"];
const skillLevelOptions = ["Beginner", "Intermediate", "Advanced"];

export const adminResourceConfigs = {
  projects: {
    title: "Projects",
    singularLabel: "Project",
    endpoint: "/admin/projects",
    publicPath: "/projects",
    pageSize: 10,
    listFilters: [
      { name: "status", label: "Status", options: ["", ...projectStatusOptions] },
      { name: "category", label: "Category", options: ["", ...projectCategoryOptions] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text" },
      { name: "shortDescription", label: "Short Description", type: "textarea", required: true },
      { name: "longDescription", label: "Long Description", type: "textarea" },
      { name: "problemSolved", label: "Problem Solved", type: "textarea" },
      { name: "techStack", label: "Tech Stack", type: "array" },
      { name: "features", label: "Features", type: "array" },
      { name: "githubUrl", label: "GitHub URL", type: "text" },
      { name: "liveUrl", label: "Live URL", type: "text" },
      { name: "category", label: "Category", type: "select", options: projectCategoryOptions, defaultValue: "Backend" },
      { name: "status", label: "Status", type: "select", options: projectStatusOptions, defaultValue: "Live" },
      { name: "displayOrder", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "isFeatured", label: "Featured", type: "checkbox" },
      { name: "isPublished", label: "Published", type: "checkbox", defaultValue: true },
    ],
  },
  experience: {
    title: "Experience",
    singularLabel: "Experience entry",
    endpoint: "/admin/experience",
    publicPath: "/experience",
    pageSize: 10,
    fields: [
      { name: "company", label: "Company", type: "text", required: true },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "startDate", label: "Start Date", type: "date", required: true },
      { name: "endDate", label: "End Date", type: "date" },
      { name: "location", label: "Location", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "responsibilities", label: "Responsibilities", type: "array", placeholder: "Owned API development, led code reviews, improved deployment workflow", helperText: "Add multiple items separated by commas or new lines." },
      { name: "achievements", label: "Achievements", type: "array", placeholder: "Reduced response time by 40%, automated reporting, improved uptime", helperText: "Add multiple items separated by commas or new lines." },
      { name: "techStack", label: "Tech Stack", type: "array", placeholder: "Node.js, Express, MongoDB, Redis, Docker", helperText: "Add multiple technologies separated by commas or new lines." },
      { name: "displayOrder", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "isCurrent", label: "Current Role", type: "checkbox" },
      { name: "isPublished", label: "Published", type: "checkbox", defaultValue: true },
    ],
  },
  achievements: {
    title: "Achievements",
    singularLabel: "Achievement",
    endpoint: "/admin/achievements",
    publicPath: "/achievements",
    pageSize: 10,
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "impact", label: "Impact", type: "textarea" },
      { name: "date", label: "Date", type: "date" },
      { name: "displayOrder", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "isFeatured", label: "Featured", type: "checkbox" },
      { name: "isPublished", label: "Published", type: "checkbox", defaultValue: true },
    ],
  },
  skills: {
    title: "Skills",
    singularLabel: "Skill",
    endpoint: "/admin/skills",
    publicPath: "/skills",
    pageSize: 20,
    listFilters: [{ name: "category", label: "Category", options: ["", ...skillCategoryOptions] }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: skillCategoryOptions, defaultValue: "Backend" },
      { name: "level", label: "Level", type: "select", options: skillLevelOptions, defaultValue: "Beginner" },
      { name: "icon", label: "Icon URL", type: "text" },
      { name: "displayOrder", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "isPublished", label: "Published", type: "checkbox", defaultValue: true },
    ],
  },
  education: {
    title: "Education",
    singularLabel: "Education entry",
    endpoint: "/admin/education",
    publicPath: "/education",
    pageSize: 10,
    fields: [
      { name: "degree", label: "Degree", type: "text", required: true },
      { name: "institution", label: "Institution", type: "text", required: true },
      { name: "startYear", label: "Start Year", type: "number", required: true },
      { name: "endYear", label: "End Year", type: "number" },
      { name: "grade", label: "Grade", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "coursework", label: "Coursework", type: "array" },
      { name: "displayOrder", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "isPublished", label: "Published", type: "checkbox", defaultValue: true },
    ],
  },
};
